<?php

use Drupal\Core\Form\FormStateInterface;

function drupal_issue_2917192_module_implements_alter(&$implementations, $hook) {
	switch($hook) {
		case 'form_editor_link_dialog_alter':
			if(array_key_exists('drupal_issue_2917192', (array)$implementations)) {
				$group = $implementations['drupal_issue_2917192'];
				unset($implementations['drupal_issue_2917192']);
				$implementations['drupal_issue_2917192'] = $group;
			}
			break;
		default:
			break;
	}
}	

function drupal_issue_2917192_form_editor_link_dialog_alter(&$form, FormStateInterface $form_state, $form_id) {
	$input = array(); 
	if (isset($form_state->getUserInput()['editor_object'])) {
		$input = $form_state->getUserInput()['editor_object'];
		$form_state->set('link_element', $input);
		$form_state->setCached(TRUE);
	}
	else {
		// Retrieve the link element's attributes from form state.
		$input = $form_state->get('link_element') ?: [];
	}

	if(!$input || !is_array($input) || !array_key_exists('target',$input)) {
		$form['attributes']['target']['#default_value'] = TRUE;
	}
	$form['advanced']['#collapsed'] = FALSE;
}

